[package]
name = "magaziner"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "json"] }
scraper = "0.24"
epub-builder = "0.8"
anyhow = "1"
clap = { version = "4.5.51", features = ["derive"] }
regex = "1.12.2"
url = "2.5.7"

